mysql1:
    image: mysql_server_1 
    ports:
        - "3307:3306"
    privileged: true

mysql2:
    image: mysql_server_2 
    ports:
        - "3308:3306"
    privileged: true

mysql3:
    image: mysql_server_3 
    ports:
        - "3309:3306"
    privileged: true
